/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Evaluation, Criterion, Employee } from '../types';
import { getScoreDisposition } from './scoreSemantics';

export interface ProductionInputParams {
  empCode: string;
  empName?: string;
  period: string;
  producedUnits: number;         // تعداد تولید واقعی (قطعه)
  targetUnits: number;           // برنامه تولید مصوب (قطعه)
  actualCycleTimeSec: number;    // سایکل‌تایم واقعی (ثانیه به ازای هر قطعه)
  standardCycleTimeSec: number;  // سایکل‌تایم استاندارد مهندسی (ثانیه)
  scrapUnits: number;            // تعداد قطعات معیوب و ضایعاتی
  workingHours: number;          // کل ساعات کاری موظفی شیفت (ساعت)
  downtimeHours: number;         // ساعات توقف خط یا خرابی دستگاه (ساعت)
  notes?: string;                // توضیحات تکمیلی اپراتور یا سرپرست
}

export interface ProductionCalculationResult {
  // راندمان تولید
  efficiencyRate: number;              // درصد راندمان تولید
  productionScore: number;             // نمره ۱ تا ۵ تحقق تولید

  // سایکل تایم
  cycleTimeVarianceSec: number;        // انحراف سایکل تایم نسبت به استاندارد (ثانیه)
  cycleTimeImprovementRate: number;    // درصد بهبود یا تاخیر سایکل تایم
  cycleTimeScore: number;              // نمره ۱ تا ۵ سایکل‌تایم

  // ضایعات و کیفیت
  scrapRate: number;                   // درصد ضایعات
  ppm: number;                         // Parts Per Million
  scrapScore: number;                  // نمره ۱ تا ۵ ضایعات
  qualityRate: number;                 // درصد قطعات سالم

  // اثربخشی کلی تجهیزات (OEE)
  availabilityRate: number;            // نرخ دسترس‌پذیری (Availability)
  performanceRate: number;             // نرخ عملکرد (Performance)
  oeeRate: number;                     // درصد OEE نهایی
  oeeScore: number;                    // نمره ۱ تا ۵ شاخص OEE

  // نمره ترکیبی شاخص‌های تولید
  overallKpiScore: number;             // میانگین نمره نهایی ۱ تا ۵

  // متن توجیهی و مستندسازی اتوماتیک
  autoGeneratedSummary: string;
  badgeLevel: 'عالی (A+)' | 'مطلوب (A)' | 'متوسط (B)' | 'نیازمند بهبود (C)' | 'بحرانی (D)';
}

export type ProductionMetricKey = 'production' | 'cycleTime' | 'scrap' | 'oee';
export type ProductionCriterionMappings = Partial<Record<ProductionMetricKey, string>>;

export function parseProductionNumber(raw: string): number | null {
  const normalized = raw.trim()
    .replace(/[۰-۹]/g, digit => String('۰۱۲۳۴۵۶۷۸۹'.indexOf(digit)))
    .replace(/[٠-٩]/g, digit => String('٠١٢٣٤٥٦٧٨٩'.indexOf(digit)))
    .replace(/٫/g, '.')
    .replace(/[٬,\s]/g, '')
    .replace(/[−–]/g, '-');
  if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(normalized)) return null;
  const value = Number(normalized);
  return Number.isFinite(value) ? value : null;
}

/** Reject incomplete or physically impossible inputs instead of inventing targets, hours, or counts. */
export function validateProductionInputs(params: ProductionInputParams): string[] {
  const issues: string[] = [];
  const finite = (value: number) => Number.isFinite(value);
  if (!finite(params.producedUnits) || params.producedUnits <= 0) issues.push('تولید واقعی باید عددی بزرگ‌تر از صفر باشد.');
  if (!finite(params.targetUnits) || params.targetUnits <= 0) issues.push('برنامه مصوب تولید باید عددی بزرگ‌تر از صفر باشد.');
  if (!finite(params.actualCycleTimeSec) || params.actualCycleTimeSec <= 0) issues.push('سایکل‌تایم واقعی باید عددی بزرگ‌تر از صفر باشد.');
  if (!finite(params.standardCycleTimeSec) || params.standardCycleTimeSec <= 0) issues.push('استاندارد مهندسی سایکل‌تایم باید عددی بزرگ‌تر از صفر باشد.');
  if (!finite(params.scrapUnits) || params.scrapUnits < 0) issues.push('تعداد ضایعات نمی‌تواند منفی باشد.');
  else if (finite(params.producedUnits) && params.scrapUnits > params.producedUnits) issues.push('تعداد ضایعات نمی‌تواند از تولید واقعی بیشتر باشد.');
  if (!finite(params.workingHours) || params.workingHours <= 0) issues.push('ساعات کارکرد باید عددی بزرگ‌تر از صفر باشد.');
  if (!finite(params.downtimeHours) || params.downtimeHours < 0) issues.push('ساعات توقف نمی‌تواند منفی باشد.');
  else if (finite(params.workingHours) && params.downtimeHours > params.workingHours) issues.push('ساعات توقف نمی‌تواند از کل ساعات کارکرد بیشتر باشد.');
  if (!params.period.trim()) issues.push('دوره ارزیابی را وارد کنید.');
  if (!params.empCode.trim()) issues.push('کد پرسنلی را انتخاب کنید.');
  return issues;
}

/**
 * Calculates comprehensive industrial performance metrics from raw production parameters
 */
export function calculateProductionMetrics(params: ProductionInputParams): ProductionCalculationResult {
  const issues = validateProductionInputs(params);
  if (issues.length) throw new RangeError(issues.join(' '));
  const {
    producedUnits,
    targetUnits,
    actualCycleTimeSec,
    standardCycleTimeSec,
    scrapUnits,
    workingHours,
    downtimeHours
  } = params;

  // 1. محاسبه راندمان تولید
  const rawEfficiencyRate = (producedUnits / targetUnits) * 100;
  if (!Number.isFinite(rawEfficiencyRate)) throw new RangeError('نسبت تولید از محدوده محاسبات پشتیبانی‌شده خارج است.');
  const efficiencyRate = Number(rawEfficiencyRate.toFixed(2));
  
  let productionScore = 3;
  if (efficiencyRate >= 105) productionScore = 5;
  else if (efficiencyRate >= 100) productionScore = 4;
  else if (efficiencyRate >= 92) productionScore = 3;
  else if (efficiencyRate >= 80) productionScore = 2;
  else productionScore = 1;

  // 2. محاسبه سایکل‌تایم و انحراف نسبت به استاندارد مهندسی
  const cycleTimeVarianceSec = Number((standardCycleTimeSec - actualCycleTimeSec).toFixed(2));

  // اگر مقدار مثبت باشد یعنی سریع‌تر از استاندارد عمل کرده (بهبود)
  const rawCycleTimeImprovementRate = ((standardCycleTimeSec - actualCycleTimeSec) / standardCycleTimeSec) * 100;
  if (!Number.isFinite(rawCycleTimeImprovementRate)) throw new RangeError('نسبت سایکل‌تایم از محدوده محاسبات پشتیبانی‌شده خارج است.');
  const cycleTimeImprovementRate = Number(rawCycleTimeImprovementRate.toFixed(2));

  let cycleTimeScore = 3;
  if (cycleTimeImprovementRate >= 5) cycleTimeScore = 5;      // بیش از ۵٪ سریع‌تر از استاندارد
  else if (cycleTimeImprovementRate >= 0) cycleTimeScore = 4;  // منطبق با استاندارد یا تا ۵٪ سریع‌تر
  else if (cycleTimeImprovementRate >= -7) cycleTimeScore = 3; // انحراف جزئی تا ۷٪ تاخیر
  else if (cycleTimeImprovementRate >= -15) cycleTimeScore = 2;// تاخیر تا ۱۵٪
  else cycleTimeScore = 1;                                     // تاخیر شدید بیش از ۱۵٪

  // 3. محاسبه ضایعات و قطعات معیوب
  const safeScrap = Math.max(0, scrapUnits);
  const scrapRate = Number(((safeScrap / producedUnits) * 100).toFixed(2));
  const ppm = Math.round(scrapRate * 10000);
  const qualityRate = Number(Math.max(0, 100 - scrapRate).toFixed(2));

  let scrapScore = 3;
  if (scrapRate <= 0.8) scrapScore = 5;        // ضایعات عالی زیر ۰.۸٪
  else if (scrapRate <= 1.5) scrapScore = 4;   // ضایعات مطلوب تا ۱.۵٪
  else if (scrapRate <= 2.5) scrapScore = 3;   // ضایعات متوسط تا ۲.۵٪
  else if (scrapRate <= 4.0) scrapScore = 2;   // ضایعات بالا تا ۴٪
  else scrapScore = 1;                         // ضایعات بحرانی بیش از ۴٪

  // 4. محاسبه OEE (دسترس‌پذیری، کارایی، کیفیت)
  const safeDowntime = downtimeHours;
  const availabilityRate = Number((((workingHours - safeDowntime) / workingHours) * 100).toFixed(2));

  // کارایی بر اساس سایکل‌تایم یا راندمان
  let performanceRate = 100;
  if (standardCycleTimeSec > 0 && actualCycleTimeSec > 0) {
    performanceRate = Number(Math.min(115, (standardCycleTimeSec / actualCycleTimeSec) * 100).toFixed(2));
  } else if (efficiencyRate > 0) {
    performanceRate = Number(Math.min(115, efficiencyRate).toFixed(2));
  }

  const oeeRate = Number(((availabilityRate * performanceRate * qualityRate) / 10000).toFixed(2));

  let oeeScore = 3;
  if (oeeRate >= 85) oeeScore = 5;       // سطح کلاس جهانی (World Class OEE)
  else if (oeeRate >= 75) oeeScore = 4;  // سطح بسیار خوب
  else if (oeeRate >= 65) oeeScore = 3;  // سطح پذیرفته کارخانه‌ای
  else if (oeeRate >= 50) oeeScore = 2;  // سطح نیازمند مداخله فنی
  else oeeScore = 1;                     // سطح غیرقابل قبول

  // 5. نمره ترکیبی کل (تولید، سایکل تایم، ضایعات، OEE)
  const overallKpiScore = Number(
    ((productionScore * 0.35) + (cycleTimeScore * 0.25) + (scrapScore * 0.25) + (oeeScore * 0.15)).toFixed(2)
  );

  let badgeLevel: ProductionCalculationResult['badgeLevel'] = 'متوسط (B)';
  if (overallKpiScore >= 4.5) badgeLevel = 'عالی (A+)';
  else if (overallKpiScore >= 3.8) badgeLevel = 'مطلوب (A)';
  else if (overallKpiScore >= 2.8) badgeLevel = 'متوسط (B)';
  else if (overallKpiScore >= 2.0) badgeLevel = 'نیازمند بهبود (C)';
  else badgeLevel = 'بحرانی (D)';

  // تولید متن اتوماتیک جهت درج در پرونده و مستندات
  const cycleDiffText = cycleTimeVarianceSec >= 0
    ? `${Math.abs(cycleTimeVarianceSec)} ثانیه سریع‌تر (+${cycleTimeImprovementRate}٪)`
    : `${Math.abs(cycleTimeVarianceSec)} ثانیه کندتر (${cycleTimeImprovementRate}٪)`;

  const autoGeneratedSummary = `داده‌های خودکار خط تولید: تولید ${producedUnits.toLocaleString('fa-IR')} قطعه (تحقق ${efficiencyRate}٪)، سایکل‌تایم ${actualCycleTimeSec}s در برابر استاندارد ${standardCycleTimeSec}s (${cycleDiffText})، ضایعات ${scrapRate}٪ (${ppm.toLocaleString('fa-IR')} PPM)، توقفات خط ${safeDowntime} ساعت، شاخص OEE: ${oeeRate}٪. نمره ارزیابی کمی: ${overallKpiScore} از ۵.`;

  return {
    efficiencyRate,
    productionScore,
    cycleTimeVarianceSec,
    cycleTimeImprovementRate,
    cycleTimeScore,
    scrapRate,
    ppm,
    scrapScore,
    qualityRate,
    availabilityRate,
    performanceRate,
    oeeRate,
    oeeScore,
    overallKpiScore,
    autoGeneratedSummary,
    badgeLevel
  };
}

/**
 * Injects calculated production metrics into an existing or new Evaluation record
 */
export function applyProductionMetricsToEvaluation(
  evaluation: Evaluation,
  criteria: Criterion[],
  calculation: ProductionCalculationResult,
  params: ProductionInputParams,
  mappings: ProductionCriterionMappings = {},
): Evaluation {
  if (evaluation.status === 'locked' || evaluation.stage === 'completed') return evaluation;

  const updatedScores = evaluation.scores.map(scoreItem => {
    const criterion = criteria.find(item => item.id === scoreItem.cid);
    if (!criterion) return scoreItem;
    if (criterion.active === false) return scoreItem;
    if (criterion.scoringSource && criterion.scoringSource !== 'supervisor') return scoreItem;
    if (scoreItem.autoPopulated || ['mis', 'kasra', 'system', 'auto', 'multi_source'].includes(scoreItem.sourceType || '')) return scoreItem;
    if ((criterion.dataType && !['number', 'percentage'].includes(criterion.dataType)) || ['not_applicable', 'exempt'].includes(getScoreDisposition(scoreItem))) return scoreItem;

    const key = (Object.entries(mappings) as Array<[ProductionMetricKey, string | undefined]>).find(([, criterionId]) => criterionId === criterion.id)?.[0];
    if (!key) return scoreItem;

    const outputs: Record<ProductionMetricKey, { value: number; doc: string }> = {
      production: {
        value: calculation.productionScore,
        doc: `تولید واقعی: ${params.producedUnits.toLocaleString('fa-IR')} از ${params.targetUnits.toLocaleString('fa-IR')} (راندمان: ${calculation.efficiencyRate}٪)`,
      },
      cycleTime: {
        value: calculation.cycleTimeScore,
        doc: `سایکل‌تایم واقعی: ${params.actualCycleTimeSec} ثانیه (استاندارد: ${params.standardCycleTimeSec} ثانیه | تغییر: ${calculation.cycleTimeImprovementRate}٪)`,
      },
      scrap: {
        value: calculation.scrapScore,
        doc: `نرخ ضایعات: ${calculation.scrapRate}٪ (${params.scrapUnits.toLocaleString('fa-IR')} عدد معیوب | ${calculation.ppm.toLocaleString('fa-IR')} PPM)`,
      },
      oee: {
        value: calculation.oeeScore,
        doc: `شاخص اثربخشی کلی تجهیزات: ${calculation.oeeRate}٪ (دسترس‌پذیری: ${calculation.availabilityRate}٪ | کارایی: ${calculation.performanceRate}٪ | کیفیت: ${calculation.qualityRate}٪)`,
      },
    };
    return {
      ...scoreItem,
      value: outputs[key].value,
      scoreStatus: 'scored' as const,
      sourceType: scoreItem.sourceType || 'supervisor',
      autoPopulated: false,
      doc: outputs[key].doc,
    };
  });

  const generatedNote = `[محاسبات تولید خودکار]: ${calculation.autoGeneratedSummary}`;
  const preservedNote = (evaluation.note || '')
    .split(/\r?\n/)
    .filter(line => !line.startsWith('[محاسبات تولید خودکار]:'))
    .join('\n')
    .trim();

  return {
    ...evaluation,
    scores: updatedScores,
    note: preservedNote ? `${preservedNote}\n\n${generatedNote}` : generatedNote,
  };
}
